package server

import "net/http"

func (a *App) productRoutes(m *http.ServeMux) {
	m.HandleFunc("GET /healthz", a.healthz)
	m.HandleFunc("GET /api/config", a.auth(a.getConfig))
	m.HandleFunc("POST /api/workspaces", a.auth(a.createWorkspace))
	m.HandleFunc("GET /api/me", a.auth(a.getMe))
	m.HandleFunc("PATCH /api/me", a.auth(a.updateMe))
	m.HandleFunc("GET /api/workspaces", a.auth(a.listWorkspaces))
	m.HandleFunc("GET /api/workspaces/{id}", a.auth(a.getWorkspace))
	m.HandleFunc("PATCH /api/workspaces/{id}", a.auth(a.updateWorkspace))
	m.HandleFunc("DELETE /api/workspaces/{id}", a.auth(a.deleteWorkspace))
	m.HandleFunc("GET /api/tokens", a.auth(a.listPersonalAccessTokens))
	m.HandleFunc("POST /api/tokens", a.auth(a.createPersonalAccessToken))
	m.HandleFunc("DELETE /api/tokens/{id}", a.auth(a.revokePersonalAccessToken))
	m.HandleFunc("GET /api/workspaces/{id}/members", a.auth(a.listWorkspaceMembers))
	m.HandleFunc("POST /api/workspaces/{id}/members", a.auth(a.addWorkspaceMember))
	m.HandleFunc("POST /api/agents", a.auth(a.withWorkspaceRole(RoleAdmin, a.createAgent)))
	m.HandleFunc("GET /api/agents", a.auth(a.listAgents))
	m.HandleFunc("GET /api/agents/{id}", a.auth(a.getAgent))
	m.HandleFunc("PATCH /api/agents/{id}", a.auth(a.updateAgent))
	m.HandleFunc("POST /api/agents/{id}/archive", a.auth(a.archiveAgent))
	m.HandleFunc("POST /api/agents/{id}/restore", a.auth(a.restoreAgent))
	m.HandleFunc("GET /api/agents/{id}/skills", a.auth(a.listAgentSkills))
	m.HandleFunc("PUT /api/agents/{id}/skills", a.auth(a.setAgentSkills))
	m.HandleFunc("GET /api/issues/search", a.auth(a.searchIssues))
	m.HandleFunc("GET /api/issues/grouped", a.auth(a.groupedIssues))
	m.HandleFunc("GET /api/issues/child-progress", a.auth(a.childIssueProgress))
	m.HandleFunc("POST /api/issues/batch-update", a.auth(a.batchUpdateIssues))
	m.HandleFunc("POST /api/issues/batch-delete", a.auth(a.batchDeleteIssues))
	m.HandleFunc("POST /api/issues", a.auth(a.withWorkspaceRole(RoleMember, a.createIssue)))
	m.HandleFunc("POST /api/issues/quick-create", a.auth(a.withWorkspaceRole(RoleMember, a.quickCreateIssue)))
	m.HandleFunc("GET /api/issues", a.auth(a.listIssues))
	m.HandleFunc("GET /api/issues/{id}", a.auth(a.getIssue))
	m.HandleFunc("PATCH /api/issues/{id}", a.auth(a.updateIssue))
	m.HandleFunc("DELETE /api/issues/{id}", a.auth(a.deleteIssue))
	m.HandleFunc("POST /api/issues/{id}/comments", a.auth(a.createComment))
	m.HandleFunc("GET /api/issues/{id}/comments", a.auth(a.listComments))
	m.HandleFunc("GET /api/issues/{id}/timeline", a.auth(a.issueTimeline))
	m.HandleFunc("GET /api/issues/{id}/children", a.auth(a.listChildIssues))
	m.HandleFunc("GET /api/issues/{id}/attachments", a.auth(a.listIssueAttachments))
	m.HandleFunc("GET /api/issues/{id}/labels", a.auth(a.listIssueLabels))
	m.HandleFunc("POST /api/issues/{id}/labels", a.auth(a.attachIssueLabel))
	m.HandleFunc("DELETE /api/issues/{id}/labels/{labelId}", a.auth(a.detachIssueLabel))
	m.HandleFunc("POST /api/attachments", a.auth(a.createAttachment))
	m.HandleFunc("GET /api/attachments/{id}", a.auth(a.getAttachment))
	m.HandleFunc("GET /api/attachments/{id}/content", a.auth(a.getAttachmentContent))
	m.HandleFunc("DELETE /api/attachments/{id}", a.auth(a.deleteAttachment))
	m.HandleFunc("PUT /api/comments/{commentId}", a.auth(a.updateComment))
	m.HandleFunc("DELETE /api/comments/{commentId}", a.auth(a.deleteComment))
	m.HandleFunc("POST /api/comments/{commentId}/resolve", a.auth(a.resolveComment))
	m.HandleFunc("DELETE /api/comments/{commentId}/resolve", a.auth(a.unresolveComment))
	m.HandleFunc("GET /api/labels", a.auth(a.listLabels))
	m.HandleFunc("POST /api/labels", a.auth(a.withWorkspaceRole(RoleMember, a.createLabel)))
	m.HandleFunc("GET /api/labels/{id}", a.auth(a.getLabel))
	m.HandleFunc("PATCH /api/labels/{id}", a.auth(a.updateLabel))
	m.HandleFunc("DELETE /api/labels/{id}", a.auth(a.deleteLabel))
	m.HandleFunc("GET /api/skills", a.auth(a.listSkills))
	m.HandleFunc("POST /api/skills", a.auth(a.createSkill))
	m.HandleFunc("POST /api/skills/import", a.auth(a.importSkill))
	m.HandleFunc("GET /api/skills/{id}", a.auth(a.getSkill))
	m.HandleFunc("PATCH /api/skills/{id}", a.auth(a.updateSkill))
	m.HandleFunc("DELETE /api/skills/{id}", a.auth(a.deleteSkill))
	m.HandleFunc("GET /api/skills/{id}/files", a.auth(a.listSkillFiles))
	m.HandleFunc("PUT /api/skills/{id}/files", a.auth(a.upsertSkillFile))
	m.HandleFunc("DELETE /api/skills/{id}/files/{fileId}", a.auth(a.deleteSkillFile))
	m.HandleFunc("GET /api/events/stream", a.auth(a.eventsStream))
	m.HandleFunc("POST /api/connected/resources", a.auth(a.withWorkspaceRole(RoleAdmin, a.createConnectedResource)))
	m.HandleFunc("GET /api/connected/resources", a.auth(a.listConnectedResources))
	m.HandleFunc("PATCH /api/connected/resources/{id}", a.auth(a.updateConnectedResource))
	m.HandleFunc("DELETE /api/connected/resources/{id}", a.auth(a.deleteConnectedResource))
	m.HandleFunc("POST /api/connected/resources/{id}/test", a.auth(a.testConnectedResourceRoute))
	m.HandleFunc("POST /api/connected/resources/{id}/sync", a.auth(a.syncConnectedResourceRoute))
	m.HandleFunc("GET /api/connected/items", a.auth(a.listConnectedItems))
	m.HandleFunc("GET /api/connected/items/{id}", a.auth(a.getConnectedItem))
	m.HandleFunc("PATCH /api/connected/items/{id}", a.auth(a.updateConnectedItem))
	m.HandleFunc("GET /api/connected/actions", a.auth(a.listConnectedActions))
	m.HandleFunc("POST /api/connected/actions", a.auth(a.createConnectedAction))
	m.HandleFunc("POST /api/connected/actions/{id}/approve", a.auth(a.approveConnectedAction))
	m.HandleFunc("POST /api/connected/actions/{id}/cancel", a.auth(a.cancelConnectedAction))
	m.HandleFunc("GET /api/connected/sync-runs", a.auth(a.listConnectedSyncRuns))
	m.HandleFunc("POST /api/todos", a.auth(a.withWorkspaceRole(RoleMember, a.createTodo)))
	m.HandleFunc("GET /api/todos", a.auth(a.listTodos))
	m.HandleFunc("PATCH /api/todos/{id}", a.auth(a.updateTodo))
	m.HandleFunc("POST /api/todos/{id}/complete", a.auth(a.completeTodo))
	m.HandleFunc("POST /api/todos/{id}/reopen", a.auth(a.reopenTodo))
	m.HandleFunc("GET /api/assignee-frequency", a.auth(a.assigneeFrequency))
	m.HandleFunc("GET /api/inbox", a.auth(a.listInbox))
	m.HandleFunc("GET /api/inbox/unread-count", a.auth(a.inboxUnreadCount))
	m.HandleFunc("POST /api/inbox/mark-all-read", a.auth(a.inboxMarkAllRead))
	m.HandleFunc("POST /api/inbox/archive-all", a.auth(a.inboxArchiveAll))
	m.HandleFunc("POST /api/inbox/archive-all-read", a.auth(a.inboxArchiveRead))
	m.HandleFunc("PATCH /api/inbox/{id}/read", a.auth(a.inboxRead))
	m.HandleFunc("PATCH /api/inbox/{id}/archive", a.auth(a.inboxArchive))
	m.HandleFunc("POST /api/squads", a.auth(a.withWorkspaceRole(RoleAdmin, a.createSquad)))
	m.HandleFunc("GET /api/squads", a.auth(a.listSquads))
	m.HandleFunc("GET /api/squads/{id}", a.auth(a.getSquad))
	m.HandleFunc("PATCH /api/squads/{id}", a.auth(a.updateSquad))
	m.HandleFunc("DELETE /api/squads/{id}", a.auth(a.deleteSquad))
	m.HandleFunc("GET /api/squads/{id}/members", a.auth(a.listSquadMembers))
	m.HandleFunc("POST /api/squads/{id}/members", a.auth(a.withWorkspaceRole(RoleAdmin, a.addSquadMember)))
	m.HandleFunc("DELETE /api/squads/{id}/members", a.auth(a.removeSquadMember))
	m.HandleFunc("PATCH /api/squads/{id}/members/role", a.auth(a.updateSquadMemberRole))
	m.HandleFunc("POST /api/autopilots", a.auth(a.withWorkspaceRole(RoleAdmin, a.createAutopilot)))
	m.HandleFunc("GET /api/autopilots", a.auth(a.listAutopilots))
	m.HandleFunc("GET /api/autopilots/{id}", a.auth(a.getAutopilot))
	m.HandleFunc("PATCH /api/autopilots/{id}", a.auth(a.updateAutopilot))
	m.HandleFunc("DELETE /api/autopilots/{id}", a.auth(a.deleteAutopilot))
	m.HandleFunc("POST /api/autopilots/{id}/run", a.auth(a.runAutopilotNow))
	m.HandleFunc("GET /api/autopilots/{id}/runs", a.auth(a.listAutopilotRuns))
	m.HandleFunc("POST /api/autopilots/{id}/triggers", a.auth(a.createAutopilotTrigger))
	m.HandleFunc("PATCH /api/autopilots/{id}/triggers/{triggerId}", a.auth(a.updateAutopilotTrigger))
	m.HandleFunc("DELETE /api/autopilots/{id}/triggers/{triggerId}", a.auth(a.deleteAutopilotTrigger))
	m.HandleFunc("POST /api/chat/sessions", a.auth(a.createChatSession))
	m.HandleFunc("GET /api/chat/sessions", a.auth(a.listChatSessions))
	m.HandleFunc("GET /api/chat/sessions/{sessionId}", a.auth(a.getChatSession))
	m.HandleFunc("PATCH /api/chat/sessions/{sessionId}", a.auth(a.updateChatSession))
	m.HandleFunc("DELETE /api/chat/sessions/{sessionId}", a.auth(a.deleteChatSession))
	m.HandleFunc("POST /api/chat/sessions/{sessionId}/messages", a.auth(a.sendChatMessage))
	m.HandleFunc("GET /api/chat/sessions/{sessionId}/messages", a.auth(a.listChatMessages))
}
